language: python
python:
  - "2.7"
  - "3.5"
# commands to install dependencies
install: 
  - pip install https://github.com/WeblateOrg/weblate/archive/master.zip
  - pip install https://github.com/WeblateOrg/hosted/archive/master.zip
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
# commands to run tests
script: 
  - ./scripts/generate-locales
  - ./manage.py check
  - python -Wd -m coverage run --source=. ./manage.py test weblate_web
  - pycodestyle .
  - pylint --reports=n --rcfile=pylint.rc weblate_web
after_success:
  - codecov
sudo: false
cache: pip
