language: python
python:
  - "2.7"
# commands to install dependencies
install: 
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
# commands to run tests
script: 
  - ./scripts/generate-locales
  - ./manage.py check
  - coverage run --source=. ./manage.py test weblate_web
  - pep8 .
  - pylint --reports=n --rcfile=pylint.rc weblate_web
after_success:
  - codecov
sudo: false
