name: easyssh
version: 1.1.7
summary: SSH Connection Manager
description: A complete, efficient and easy-to-use manager. Create and edit connections, groups, customize the terminal, with multiple instances of the same connection.

icon: data/icons/24/com.github.muriloventuroso.easyssh.svg
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

slots:
  dbus-easyssh:
    interface: dbus
    bus: session
    name: com.github.muriloventuroso.easyssh

apps:
  easyssh:
    command: easyssh
    plugs: [x11, unity7, network]

parts:
    granite:
        plugin: cmake
        source: lp:granite/0.5
        source-type: bzr
        configflags: [-DCMAKE_BUILD_TYPE=Release, -DCMAKE_INSTALL_PREFIX=/usr, -DCMAKE_INSTALL_LIBDIR=/usr/lib]
        build-packages:
          - build-essential
          - valac
        stage-packages:
          - valac-0.30-vapi

    easyssh:
        plugin: meson
        meson-parameters:
          - --prefix=/usr
        source: https://github.com/muriloventuroso/easyssh.git
        source-type: git
        after: [granite, desktop-gtk3]
        build-packages:
            - build-essential
            - valac
            - intltool
            - libgee-0.8-dev
            - debhelper
            - libgtk-3-dev
            - libgranite-dev
            - libvte-2.91-dev
            - libjson-glib-dev
        stage-packages:
            - gobject-introspection
            - libgee-0.8-2
            - libgtk-3-0