name: easyssh
version: 1.2.0
summary: SSH Connection Manager
description: A complete, efficient and easy-to-use manager. Create and edit connections, groups, customize the terminal, with multiple instances of the same connection.

icon: data/icons/24/com.github.muriloventuroso.easyssh.svg
grade: stable
confinement: classic

slots:
  dbus-easyssh:
    interface: dbus
    bus: session
    name: com.github.muriloventuroso.easyssh

apps:
  easyssh:
    command: com.github.muriloventuroso.easyssh
    desktop: usr/share/applications/com.github.muriloventuroso.easyssh.desktop
    plugs: [network, home, x11, unity7, gsettings]
apps:
  bookworm:
    command: com.github.muriloventuroso.easyssh
    slots: [ dbus-easyssh ]
    desktop: usr/share/applications/com.github.muriloventuroso.easyssh.desktop
    plugs: [network, home, x11, unity7, gsettings]


parts:
    elementary:
        plugin: nil
        override-build: |
              add-apt-repository -y ppa:elementary-os/stable
              add-apt-repository -y ppa:elementary-os/os-patches
              echo "Package: *" > /etc/apt/preferences.d/elementary-stable
              echo "Pin: release o=LP-PPA-elementary-os-stable" >> /etc/apt/preferences.d/elementary-stable
              echo "Pin-Priority: 1000" >> /etc/apt/preferences.d/elementary-stable
              echo "Package: *" > /etc/apt/preferences.d/elementary-patches
              echo "Pin: release o=LP-PPA-elementary-os-os-patches" >> /etc/apt/preferences.d/elementary-patches
              echo "Pin-Priority: 1000" >> /etc/apt/preferences.d/elementary-patches
              apt update
              apt dist-upgrade -y
    openssh:
        plugin: cmake
        source-type: tar
        source: https://cloudflare.cdn.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-7.6p1.tar.gz
    easyssh:
        plugin: meson
        meson-parameters:
          - --prefix=/usr
        source: https://github.com/muriloventuroso/easyssh.git
        source-type: git
        after: [elementary, desktop-gnome-platform, openssh]
        build-packages:
            - build-essential
            - intltool
            - libgee-0.8-dev
            - debhelper
            - libgtk-3-dev
            - libvte-2.91-dev
            - libjson-glib-dev
        stage-packages:
            - gobject-introspection
            - libgee-0.8-2
            - libgtk-3-0
