name: easyssh
version: 1.2.0
summary: SSH Connection Manager
description: A complete, efficient and easy-to-use manager. Create and edit connections, groups, customize the terminal, with multiple instances of the same connection.

icon: data/icons/24/com.github.muriloventuroso.easyssh.svg
grade: stable
confinement: classic

slots:
  dbus-easyssh:
    interface: dbus
    bus: session
    name: com.github.muriloventuroso.easyssh

apps:
  easyssh:
    command: com.github.muriloventuroso.easyssh
    desktop: usr/share/applications/com.github.muriloventuroso.easyssh.desktop
    plugs: [network, home, x11, unity7, gsettings]

parts:
    granite:
        plugin: cmake
        source: https://github.com/elementary/granite/archive/0.5.tar.gz
        source-type: tar
        configflags: [-DCMAKE_BUILD_TYPE=Release, -DCMAKE_INSTALL_PREFIX=/usr, -DCMAKE_INSTALL_LIBDIR=/usr/lib]
        build-packages:
            - build-essential
            - libgee-0.8-dev
            - libgirepository1.0-dev
            - libgtk-3-dev
            - cmake
            - gobject-introspection

    easyssh:
        plugin: meson
        meson-parameters:
          - --prefix=/usr
        source: https://github.com/muriloventuroso/easyssh.git
        source-type: git
        after: [granite, desktop-gtk3]
        build-packages:
            - build-essential
            - valac
            - intltool
            - libgee-0.8-dev
            - debhelper
            - libgtk-3-dev
            - libgranite-dev
            - libvte-2.91-dev
            - libjson-glib-dev
        stage-packages:
            - gobject-introspection
            - libgee-0.8-2
            - libgtk-3-0
    valac:
      plugin: autotools
      source: http://download.gnome.org/sources/vala/0.38/vala-0.38.8.tar.xz
      build-packages:
         - flex    
         - bison
         - build-essential
         - libglib2.0-dev
         - libgraphviz-dev